travis:
  secure:
    BINSTAR_TOKEN: ekFW9c41lvOL2l2gs5XdTupI8yNXzFrbki5ojmwEgIz1YcSIjjHxDVxYJs9oOrHHyobkV+04vXMDUoPc6Ybel+r2mQShoszwWAPaaepFzdbmDEpK9UoUMqCjKdCnmM7wYIPPv6w6WjWJWbCo0t/ZmmVRuk1QQDnrwNzcNCfT2r8PqGT6NmjYQZ7tle3s2laT/4RCdLAM3F1nPaPGSvP4t7Ko3QFCJiLUOJEEKIRiTfj4yOBG/In8HLWThagDhIfq6ZbMP3R9twlzWmHZjF37jZoSerux22yc2pVp1svww1JrfRcSj62RXkw/FM/IHQG1YmzsYeuGHzYgNalntNByONjXpKlxLVz9ofXBKldHhXwJRBG1ZtyT8kUZ90kRkftH8ihix+VA4ALBU1mjvzpDRdPTDtfiV9fVZ5HZQ5J9u7XqwFGue9bgiTGZAsPZHz3NtSkb7XiQAbju15Wr91N+DMinBJGcYOs4iPufW2qxhg7ZoALrcJifREDWaZ/H8NA1QHcvzBOFyskV9oQRXONylFoD2N1VpHPlcSv/ZHCOKmMDHdDXJ+ahEH7IakiOQZUPr3fOsmzqgr2NuLds23Cc5V7K3GQRyWAk7pXSdHu71skvDxJ/CLPngyirCkO4kkM308L11XI1k79oYo9xRNXQYBIUXEcSR2eISq0l36IhMw0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
